#!/usr/bin/env python3
"""Expand top 30 glossary pages from ~170 words to 600+ words each."""

import os
import re

GLOSSARY_DIR = "/Users/macbookpro/Desktop/vigyanpilot/frontend/glossary"

TERMS = [
    "allele", "rt-pcr", "rna-polymerase", "qpcr", "primer-design",
    "primer", "dbsnp", "binding-affinity", "amplicon", "primer-dimer",
    "melting-temperature", "gc-content", "pcr", "taqman-probe",
    "cdna-library", "annealing-temperature", "dna-polymerase",
    "multiplex-pcr", "nested-pcr",
]

TERM_NAMES = {
    "rt-pcr": "RT-PCR", "qpcr": "qPCR", "pcr": "PCR",
    "rna-polymerase": "RNA polymerase", "dbsnp": "dbSNP",
    "dna-polymerase": "DNA polymerase",
    "taqman-probe": "TaqMan probe",
    "cdna-library": "cDNA library",
    "annealing-temperature": "annealing temperature",
}

def display_name(term):
    return TERM_NAMES.get(term, term.replace("-", " "))

# ────────────────────────────────────────────
# Content for each term: 4 sections
# ────────────────────────────────────────────

CONTENT = {}

# 1. allele
CONTENT["allele"] = {
    "mechanism": """Alleles arise from mutations such as single-nucleotide substitutions, insertions, or deletions at a specific chromosomal locus. In diploid organisms, each somatic cell carries two alleles per autosomal gene — one inherited from each parent. When both alleles are identical, the genotype is homozygous; when they differ, it is heterozygous. Allelic variation can manifest as differences in a single nucleotide (single-nucleotide polymorphism, SNP), repeat-length polymorphisms (microsatellites), or larger structural variants. The relationship between alleles follows Mendelian principles: dominant alleles mask the phenotypic expression of recessive alleles in heterozygous individuals. At the molecular level, allelic differences may alter the amino acid sequence of a protein, change regulatory elements such as promoters or enhancers, or affect mRNA splicing patterns. The frequency of each allele within a population is shaped by natural selection, genetic drift, gene flow, and mutation rate. Hardy-Weinberg equilibrium (p² + 2pq + q² = 1) describes the expected genotype frequencies under ideal conditions of random mating, no selection, and no migration. Deviations from Hardy-Weinberg proportions can indicate evolutionary forces or genotyping errors.""",

    "applications": """Allele-specific analysis is central to genome-wide association studies (GWAS), which scan millions of SNPs across large cohorts to identify genetic variants associated with complex diseases such as type 2 diabetes, coronary artery disease, and schizophrenia. In clinical genetics, allele-specific PCR and allele-specific oligonucleotide (ASO) probes are used to detect known pathogenic variants in inherited disorders like cystic fibrosis (CFTR gene) and sickle cell disease (HBB gene). Pharmacogenomics relies on characterizing alleles of drug-metabolizing enzymes such as CYP2D6, CYP2C9, and CYP2C19 to predict patient responses to medications including warfarin, clopidogrel, and tamoxifen. Forensic DNA profiling employs allele frequency databases (e.g., CODIS) across 20 short tandem repeat loci to generate random match probabilities as low as 1 in 10¹⁷. In population genetics, allele frequency spectra and fixation index (F_ST) values quantify genetic differentiation between populations.""",

    "parameters": """Key parameters in allele analysis include minor allele frequency (MAF), typically filtered at >1% for common variants or <1% for rare variants; Hardy-Weinberg equilibrium p-value threshold (commonly P > 1 × 10⁻⁶ in GWAS); imputation quality score (R² > 0.3 for well-imputed variants); call rate (>95% per SNP and per sample); and linkage disequilibrium (LD) measured by r² or D′ values. For heterozygosity analysis, observed heterozygosity (Ho) compared to expected heterozygosity (He) can indicate inbreeding or population stratification. Sample sizes for allele frequency estimation require at least n = 100 individuals for a MAF of 5% with reasonable confidence intervals.""",

    "mistakes": """A common misconception is that an allele with a higher frequency is necessarily dominant; in fact, allele frequency and dominance are independent properties. Another frequent error is assuming that Hardy-Weinberg equilibrium implies a population is not evolving, when it simply describes a specific mathematical expectation under ideal conditions. Researchers sometimes confuse "allele" with "gene" — an allele is a specific variant form, not the gene itself. In variant calling from next-generation sequencing data, failing to account for strand bias or mapping quality can produce false-positive allele calls. Pool-seq studies must correct for sequencing errors and unequal allele representation in pooled samples."""
}

# 2. rt-pcr
CONTENT["rt-pcr"] = {
    "mechanism": """RT-PCR proceeds in two sequential stages. First, reverse transcriptase, an RNA-dependent DNA polymerase derived from retroviruses such as Moloney Murine Leukemia Virus (MMLV) or Avian Myeloblastosis Virus (AMV), synthesizes a complementary DNA (cDNA) strand from an RNA template. The reaction uses either random hexamers, oligo-dT primers (which anneal to the poly-A tail of mRNA), or gene-specific primers to initiate reverse transcription at 37–42 °C for 30–60 minutes. After the reverse transcriptase is heat-inactivated at 70 °C for 15 minutes, the cDNA serves as the template for conventional PCR amplification using a thermostable DNA polymerase such as Taq or Pfu. The PCR phase cycles through denaturation (94–98 °C, 15–30 s), annealing (50–65 °C, 20–40 s), and extension (72 °C, 30 s/kb) for 25–40 cycles. In two-step RT-PCR, reverse transcription and PCR are performed sequentially in separate tubes; one-step RT-PCR combines both enzymes in a single tube for higher throughput and reduced contamination risk.""",

    "applications": """RT-PCR is the gold-standard method for gene expression analysis, enabling relative quantification using the ΔΔCt method with normalization to housekeeping genes such as GAPDH, ACTB, or 18S rRNA. In virology, RT-PCR is the primary diagnostic tool for detecting RNA viruses including SARS-CoV-2 (COVID-19), influenza, HIV, hepatitis C virus (HCV), and Zika virus. The technique can detect as few as 10–100 viral RNA copies per reaction. In oncology, RT-PCR is used to detect fusion transcripts such as BCR-ABL in chronic myeloid leukemia, with sensitivity down to 1 in 10⁵ cells. It also enables splicing variant analysis, alternative transcript characterization, and microRNA quantification. In plant and animal biotechnology, RT-PCR validates transgene expression in genetically modified organisms.""",

    "parameters": """Critical RT-PCR parameters include the choice of reverse transcriptase (MMLV optimal at 37 °C; AMV at 42 °C with higher thermostability); primer concentration (0.5–2 μM for random hexamers, 0.1–0.5 μM for gene-specific primers); dNTP concentration (0.5–1 mM each); RNA input amount (1 pg to 1 μg total RNA); and reaction volume (10–50 μL). For the PCR phase, Taq DNA polymerase optimal extension temperature is 72 °C; annealing temperature is typically 3–5 °C below the primer Tm; cycle number should avoid the plateau phase; and MgCl₂ concentration (1.5–2.5 mM) affects enzyme activity and specificity.""",

    "mistakes": """A frequent error is using degraded RNA, which leads to underrepresentation of target transcripts and high Cq values. Researchers often confuse RT-PCR (endpoint or real-time) with qPCR — RT-PCR specifically includes the reverse transcription step for RNA templates. Inadequate DNase treatment can produce false-positive signals from contaminating genomic DNA, especially when primers span a single exon. Using too much RNA template (>1 μg) can inhibit the reverse transcriptase reaction. The absence of no-reverse-transcriptase controls (no-RT controls) makes it impossible to distinguish genuine RNA-derived signal from genomic DNA contamination."""
}

# 3. rna-polymerase
CONTENT["rna-polymerase"] = {
    "mechanism": """RNA polymerase (RNAP) catalyzes the template-directed synthesis of RNA from ribonucleoside triphosphates (NTPs), using DNA as the template strand. In prokaryotes, a single RNA polymerase core enzyme (α₂ββ′ω) associates with a sigma (σ) factor to recognize promoter sequences at −10 and −35 boxes. Transcription initiation begins when the holoenzyme binds the promoter, unwinds approximately 12–15 base pairs of DNA, and incorporates the first NTP (typically a purine, ATP or GTP). Promoter escape occurs after 8–12 nucleotides are synthesized. Elongation proceeds at 20–50 nucleotides per second in bacteria and 20–30 nt/s in eukaryotes. In eukaryotes, three distinct RNA polymerases exist: RNA Pol I transcribes ribosomal RNA (45S pre-rRNA) in the nucleolus; RNA Pol II transcribes mRNA, snRNA, and microRNA precursors; and RNA Pol III transcribes tRNA, 5S rRNA, and U6 snRNA. Pol II requires the assembly of general transcription factors (TFIIA, TFIIB, TFIID, TFIIE, TFIIF, TFIIH) at the core promoter before initiation.""",

    "applications": """RNA polymerase is the target of the antibiotic rifampicin, which binds to the β subunit of bacterial RNAP and blocks RNA chain elongation beyond 2–3 nucleotides. In molecular biology, T7 RNA polymerase (from bacteriophage T7) is widely used for in vitro transcription to synthesize RNA probes, mRNA for translation assays, and guide RNAs for CRISPR-Cas9 applications. RNA polymerase II ChIP-seq (chromatin immunoprecipitation followed by sequencing) maps genome-wide transcription start sites and identifies promoter-proximal pausing. Promoter engineering uses RNAP specificity to design synthetic gene circuits. Studies of RNAP pausing and backtracking provide insights into transcriptional regulation and the mechanisms of elongation factors such as TFIIS.""",

    "parameters": """Key parameters include promoter strength, quantified as ΔG of RNAP-promoter binding (−5 to −15 kcal/mol); elongation rate (20–50 nt/s in E. coli, 20–30 nt/s in Pol II); processivity (transcripts up to 2–3 Mb in eukaryotes); termination efficiency (>90% for Rho-independent terminators); NTP concentration (cellular 0.5–5 mM each); and transcription bubble size (12–15 bp). RNA polymerase fidelity is approximately 10⁴ to 10⁵ with proofreading via backtracking and cleavage. Inhibitor sensitivity varies: α-amanitin (Pol II IC₅₀ = 1–10 ng/mL), actinomycin D (intercalation), and rifampicin (bacterial RNAP IC₅₀ = 0.1 μg/mL).""",

    "mistakes": """A common misconception is that RNA polymerase creates RNA from scratch; it actually requires a DNA template and initiates with NTPs complementary to the template strand. Researchers sometimes confuse RNA polymerase with reverse transcriptase (which uses an RNA template to make DNA) or with primase (which makes short RNA primers for DNA replication). In run-on transcription assays, failing to properly permeabilize cells results in underrepresentation of elongating RNAP complexes. Overexpression of T7 RNA polymerase in E. coli can cause metabolic burden and plasmid instability due to high-level transcription of target genes."""
}

# 4. qpcr
CONTENT["qpcr"] = {
    "mechanism": """qPCR monitors amplification in real time by measuring fluorescence emitted during each thermal cycle. The fluorescence signal is proportional to the amount of double-stranded DNA (or hydrolysis probe cleavage product) accumulating in the reaction. The key measurement is the quantification cycle (Cq or Ct), defined as the cycle at which the fluorescence signal rises above a threshold (typically 10 standard deviations above background). During the exponential phase of PCR, the amount of target DNA doubles each cycle, making the Cq value inversely proportional to the log of the initial template quantity. The relationship follows the equation N = N₀ × (1 + E)^Cq, where N is the target copy number, N₀ is the initial copy number, and E is amplification efficiency (ideally 1.0–2.0). Standard curves using serial dilutions of known template (10ⁱ to 10⁸ copies) establish the linear dynamic range and amplification efficiency. The MIQE guidelines (Minimum Information for Publication of Quantitative Real-Time PCR Experiments) mandate reporting of Cq values, efficiency, and standard curve parameters.""",

    "applications": """qPCR is used for absolute quantification of viral load (HIV, HBV, HCV, SARS-CoV-2) with dynamic ranges spanning 7–8 orders of magnitude. In gene expression analysis, relative quantification using the comparative Ct (ΔΔCt) method compares target gene expression to reference genes across experimental conditions. Copy number variation (CNV) analysis uses qPCR to determine gene dosage in conditions such as HER2 amplification in breast cancer and SMN1 deletion in spinal muscular atrophy. Allelic discrimination assays detect SNPs through probe hybridization or melt curve analysis. Genetically modified organism (GMO) detection in food products relies on qPCR targeting transgenic elements such as 35S promoter and NOS terminator. Pathogen detection in clinical, food, and environmental samples benefits from qPCR's sensitivity and speed.""",

    "parameters": """Critical qPCR parameters include amplification efficiency (90–110% or E = 1.8–2.0); R² of standard curve (>0.98); Cq range (typically 15–35 cycles); threshold setting (10–50 times the standard deviation of baseline fluorescence); primer concentration (50–900 nM); probe concentration (100–250 nM); MgCl₂ concentration (3–6 mM); reaction volume (10–20 μL); and thermal cycling conditions (95 °C for 10 min for polymerase activation, then 40–45 cycles of 95 °C for 15 s and 60 °C for 30–60 s). Melt curve analysis for SYBR Green assays requires a ramp from 60 to 95 °C at 0.1–0.3 °C/s.""",

    "mistakes": """The most common error is reporting Cq values without considering amplification efficiency, leading to inaccurate fold-change calculations. Another frequent problem is using a single reference gene without validating its stability across experimental conditions — the minimum requirement is two validated reference genes. Pipetting errors in the nanoliter range significantly affect Cq reproducibility, with coefficients of variation of 0.5–2% in well-performed triplicates. Melting curve analysis is essential for SYBR Green assays but often omitted, allowing primer-dimer amplification to masquerade as genuine signal. Normalizing to total RNA mass is unreliable; genomic DNA contamination should be confirmed with no-RT controls. Researchers frequently set the threshold manually below background, inflating apparent Cq differences."""
}

# 5. primer-design
CONTENT["primer-design"] = {
    "mechanism": """Primer design begins with identifying a conserved target region within the DNA sequence of interest (typically 100–1000 bp for standard PCR). The forward and reverse primers flank the target, oriented such that their 3' ends point toward each other. Candidate primers are evaluated using thermodynamic calculations based on the nearest-neighbor model (SantaLucia 1998), which predicts melting temperature (Tm) from base-stacking enthalpies and entropies. The algorithm computes Tm using the formula Tm = ΔH°/(ΔS° + R ln(C/4)) for self-complementary primers, accounting for salt concentration (typically 50 mM Na⁺ or 1.5–2.5 mM Mg²⁺) and primer concentration (0.1–1 μM). GC content ideally ranges from 40–60%, with 3' end stability checked to prevent false priming. Secondary structure prediction evaluates the free energy of hairpins and self-dimers, while cross-dimer analysis assesses interactions between forward and reverse primers. BLAST or sequence-similarity searches confirm specificity against the target genome. Modern primer design tools such as Primer3, Primer-BLAST, and VPrime 2.0 automate these evaluations across 20–30 distinct checks.""",

    "applications": """Primer design is fundamental to PCR-based applications including diagnostic assay development, cloning (restriction-site incorporation), site-directed mutagenesis, bisulfite sequencing PCR (MSP), and multiplex PCR for pathogen detection panels. In qPCR, primer design must accommodate amplicons of 70–150 bp with Tm matching between primer pairs within 1 °C. Degenerate primers target conserved regions across homologous genes from different species. Tiling primer sets arrayed across genomic regions enable targeted next-generation sequencing panel design. In CRISPR applications, guide RNA design (crRNA) follows similar principles of specificity and minimal off-target homology.""",

    "parameters": """Key primer design parameters include: primer length (18–25 nt); Tm (52–58 °C for standard PCR, 58–60 °C for qPCR); Tm difference between paired primers (<5 °C); GC content (40–60%); 3' end stability (ΔG > −9 kcal/mol); maximum 3' GC clamp length (3–4 G/C bases); absence of long mononucleotide runs (>4 identical bases); maximum self-complementarity score (<3 consecutive bases matching); maximum pair complementarity score (<3 bases); amplicon length (70–150 bp for qPCR, 200–1000 bp for standard PCR); and specificity (0 mismatches in last 5 bases at 3' end against non-target sequences, or >2 mismatches total).""",

    "mistakes": """A widespread error is designing primers with complementary 3' ends, which promotes primer-dimer formation even when the rest of the primer is well-designed. Researchers often choose primers with Tm differences exceeding 5 °C between forward and reverse, leading to biased amplification. Another common oversight is failing to check for repetitive elements (Alu, LINE) within the primer sequence, causing nonspecific amplification across the genome. Many users rely solely on default Primer3 parameters without adjusting salt concentration, primer concentration, or Mg²⁺ to match their experimental conditions. Checking primer specificity by BLAST against the intended genome is frequently skipped, resulting in off-target amplification."""
}

# 6. primer
CONTENT["primer"] = {
    "mechanism": """Primers function by providing a free 3'-hydroxyl group that DNA polymerase requires to initiate nucleotide polymerization. During the annealing step of PCR, the primer diffuses in solution and hybridizes to its complementary target sequence through Watson-Crick base pairing. The stability of this hybridization is governed by the free energy of duplex formation (ΔG), which depends on the number and type of hydrogen bonds formed (two between A-T, three between G-C) plus base-stacking interactions between adjacent base pairs. The 3'-terminal nucleotide is the most critical for extension specificity: a single mismatch at the 3' end can reduce amplification efficiency by 100–1000-fold, while mismatches in the central or 5' region are more tolerated. DNA polymerase extends from the 3' end by incorporating dNTPs complementary to the template strand, proceeding in a 5'-to-3' direction at rates depending on the polymerase (Taq: 60 nt/s at 72 °C; Phusion: 100 nt/s). After extension, the newly synthesized strand serves as a template in subsequent cycles, enabling exponential amplification with a theoretical doubling efficiency of 2ᵗ after n cycles.""",

    "applications": """Primers are indispensable in PCR amplification for cloning, sequencing (Sanger and next-generation), genotyping by microsatellite analysis, and allele-specific PCR. In molecular diagnostics, primers target pathogen-specific genes for detection of infectious agents including SARS-CoV-2 (N, RdRp, E genes), Mycobacterium tuberculosis (IS6110), and Plasmodium species (18S rRNA). Degenerate primers amplify homologous sequences from related species for phylogenetic analysis. In synthetic biology, primers incorporate restriction sites, promoter sequences, or epitope tags for vector construction. Barcoded primers with unique molecular identifiers (UMIs) reduce amplification bias in single-cell RNA-seq. Methylation-specific primers distinguish methylated from unmethylated CpG sites in bisulfite-converted DNA.""",

    "parameters": """Primer quality parameters include length (18–25 nt for standard PCR, 15–20 nt for allele-specific PCR); Tm (52–58 °C, calculated via nearest-neighbor model); pyrimidine/purine balance; absence of 3' complementarity; GC content (40–60%); maximum repeat length (mononucleotide runs <4, dinucleotide repeats <4); secondary structure ΔG (> −3 kcal/mol for hairpins, > −5 kcal/mol for self-dimers); specificity (BLAST E-value threshold < 0.01); and synthesis purity (>90% full-length product for desalted primers, >95% for HPLC-purified). Primer working concentration in PCR is typically 0.1–1 μM per primer. For multiplex PCR, each primer's concentration may be adjusted by 0.5–2 × the standard to balance amplification across targets.""",

    "mistakes": """A common error is using primers with high GC content (>65%), which increases the risk of nonspecific annealing and secondary structure formation. Researchers often order primers without specifying purification (desalted is sufficient for routine PCR but HPLC-purified is needed for qPCR probes or in vitro transcription). Storing primers at incorrect temperatures (they should be at −20 °C in TE buffer, 100 μM stock) leads to degradation. Another mistake is failing to resuspend primers to the correct concentration after synthesis, resulting in inaccurate molar amounts in PCR reactions. Primers with 3' T residues are more prone to mispriming because T has weaker stacking interactions."""
}

# 7. dbsnp
CONTENT["dbsnp"] = {
    "mechanism": """dbSNP (Single Nucleotide Polymorphism Database) is a public-domain repository maintained by the National Center for Biotechnology Information (NCBI) that catalogs small genetic variations including single-nucleotide polymorphisms (SNPs), small insertions and deletions (indels), microsatellites, and short tandem repeats. Each variant is assigned a unique reference SNP cluster ID (rs number, e.g., rs53576 for the oxytocin receptor gene). Submissions from researchers worldwide undergo validation through multiple independent submissions, population frequency studies, and linkage analysis. Variants are annotated with their genomic location (build GRCh38 or T2T-CHM13), allele frequencies across global populations (1000 Genomes Project, gnomAD), functional consequence (missense, synonymous, nonsense, intronic), clinical significance (ClinVar), and validation status. The database integrates data from large-scale sequencing projects such as the 1000 Genomes Project (84.7 million variants), TOPMed (485 million variants), and gnomAD (v3.1, 76,156 whole genomes). dbSNP build 156 contains over 1 billion submitted records.""",

    "applications": """dbSNP is the primary resource for selecting tag SNPs for GWAS genotyping arrays such as the Illumina Infinium Global Screening Array (GSA, 700,000+ markers). Researchers use rs identifiers to link SNP data across publications, databases (ClinVar, GWAS Catalog, PharmGKB), and laboratory assays. In pharmacogenomics, dbSNP entries for CYP2C19*2 (rs4244285), CYP2C9*2 (rs1799853), and VKORC1 (rs9923231) guide drug-dosing decisions. In population genetics, SNP allele frequencies from dbSNP are used to calculate F_ST, heterozygosity, and principal component ancestry estimates. Forensic panels utilize dbSNP-validated markers for ancestry-informative SNP (AISNP) panels. Clinical laboratories use dbSNP to filter out common benign variants from candidate variant lists in diagnostic sequencing.""",

    "parameters": """Key dbSNP parameters include rs ID for variant identification; genomic coordinates (chromosome, position, strand); reference and alternate alleles; variant type (SNV, indel, MNV); allele frequency (global and subpopulation); validation status (by frequency, by two-hit, or cluster); functional class (missense, synonymous, intron, UTR, splice site); ClinVar significance (pathogenic, benign, uncertain); quality metrics (quality score, coverage depth); and population-specific data from 1000 Genomes, gnomAD, ALFA, and TOPMed. Minor allele frequency thresholds typically used are >0.01 for common variants and <0.01 for rare variants. Submission requirements include flanking sequence (100 bp on each side) and at least two independent observations for validation.""",

    "mistakes": """A common error is assuming that an rs number without population frequency data represents a real variant; many dbSNP entries were computationally predicted and have not been validated. Researchers sometimes use outdated dbSNP builds (e.g., build 144 instead of 156), missing newly curated variants and frequency data. Another misconception is that a variant annotated as "pathogenic" in ClinVar is definitively disease-causing regardless of the submitter's evidence level. Users often confuse "reference allele" (the sequence in the reference genome) with "wild-type" or "major allele" — the reference genome may carry a rare or even pathogenic allele at particular loci. Failing to lift over coordinates between genome builds (GRCh37 vs GRCh38) leads to annotation errors."""
}

# 8. binding-affinity
CONTENT["binding-affinity"] = {
    "mechanism": """Binding affinity quantifies the strength of the reversible non-covalent interaction between a ligand (small molecule, peptide, antibody) and its target (protein, nucleic acid, receptor). It is most commonly expressed as the dissociation constant Kd, which is the equilibrium concentration of free ligand at which half of the target binding sites are occupied. Kd relates to the association (k_on) and dissociation (k_off) rate constants by Kd = k_off/k_on. The Gibbs free energy of binding (ΔG) is related to Kd by ΔG = RT ln(Kd), where R = 1.987 cal/(mol·K) and T is temperature in Kelvin. At 25 °C, a Kd of 1 nM corresponds to a ΔG of approximately −12.3 kcal/mol. Strong binding typically yields Kd values in the low nanomolar (1–100 nM) for drug-like small molecules or picomolar (1–1000 pM) for antibodies. The binding energy arises from hydrogen bonds (1–5 kcal/mol each), van der Waals interactions (0.5–2 kcal/mol per atom pair), hydrophobic effects (0.02–0.04 kcal/mol per Å² of buried surface area), and electrostatic interactions.""",

    "applications": """Binding affinity measurements drive drug discovery hit identification (Kd < 10 μM), lead optimization (Kd < 100 nM), and candidate selection (Kd < 10 nM). Surface plasmon resonance (SPR) provides real-time k_on and k_off measurements for label-free affinity determination. Isothermal titration calorimetry (ITC) measures ΔG, ΔH, and ΔS directly, revealing thermodynamic signatures of binding. In antibody development, affinity maturation targets Kd improvements from micromolar to picomolar ranges through directed evolution or rational mutagenesis of complementarity-determining regions. In fragment-based drug discovery, initial fragments with millimolar affinity are optimized to nanomolar leads. For nucleic acid interactions, binding affinity between primers and templates determines PCR specificity, with perfectly matched primers having up to 10⁴-fold higher affinity than those with 3' mismatches.""",

    "parameters": """Binding affinity parameters include dissociation constant Kd (units: M to pM); IC50 (half-maximal inhibitory concentration, μM to nM); EC50 (half-maximal effective concentration); Hill coefficient (n, cooperativity, typically 1–4); k_on (association rate, 10³–10⁷ M⁻¹s⁻¹); k_off (dissociation rate, 10⁻⁵–10¹ s⁻¹); residence time (1/k_off, seconds to hours); ligand efficiency (LE = ΔG/heavy atom count, >0.3 kcal/mol/atom recommended for leads); lipophilic ligand efficiency (LLE = pIC50 − logP); and selectivity ratio (Kd_target/Kd_off-target, >100-fold preferred). For SPR, typical protein immobilization levels are 100–1000 RU with ligand concentrations ranging from 0.1 nM to 10 μM.""",

    "mistakes": """A common error is equating IC50 with Kd without accounting for assay conditions (IC50 approximates Kd only under Cheng-Prusoff assumptions when substrate concentration equals K_m). Overinterpreting binding affinity without kinetic data (k_on and k_off) misses the distinction between fast-on/fast-off vs slow-on/slow-off binders, which dramatically affects drug efficacy. Researchers often report binding affinity without specifying temperature, buffer pH, salt concentration, or cofactors, making comparisons across studies invalid. In docking studies, scoring functions correlate only modestly with experimental affinities (R² = 0.3–0.6). Another mistake is assuming that tighter binding always translates to better efficacy, ignoring bioavailability, clearance, and toxicity."""
}

# 9. amplicon
CONTENT["amplicon"] = {
    "mechanism": """An amplicon is the DNA product generated by PCR amplification, defined by the sequences of the forward and reverse primers and the DNA region between them. During PCR, the amplicon doubles each cycle, accumulating exponentially: after n cycles of ideal amplification, the amplicon copy number equals 2^n × N₀, where N₀ is the initial template copy number. The amplicon length influences amplification efficiency: short amplicons (70–150 bp) amplify more efficiently than long ones (>1 kb) because shorter products denature and renature more rapidly during thermal cycling. The amplicon's Tm can be predicted from its GC content and length, and the amplicon sequence determines its melting curve profile in qPCR melt analysis. In standard PCR, amplicons are resolved by agarose gel electrophoresis (typically 1–2% agarose, stained with ethidium bromide or SYBR Safe) and visualized as discrete bands. The amplicon size is confirmed against a DNA ladder (e.g., 100 bp or 1 kb ladder). Sanger sequencing of amplicons verifies their identity with >99% accuracy for fragments up to 800 bp.""",

    "applications": """Amplicons form the basis of virtually all PCR-based assays. In diagnostic testing, SARS-CoV-2 detection amplifies amplicons of the N gene (72 bp), RdRp gene, and E gene targets. In forensics, STR amplicons (75–450 bp) from 20 core CODIS loci enable human identification from sub-nanogram DNA quantities. Amplicon-based next-generation sequencing (AmpliSeq, Haloplex) targets hundreds to thousands of genomic regions in parallel for cancer hotspot panels (e.g., 50-gene pan-cancer panels). Long-range PCR targets amplicons of 10–30 kb for genome walking, structural variant detection, and phasing of distant variants. In viral load monitoring, HIV-1 amplicons in the gag, pol, and env regions are quantified by qPCR. Amplicon melting analysis enables genotyping through sequence-specific melting temperatures (Tm shifts of 1–4 °C per SNP).""",

    "parameters": """Amplicon parameters include length (qPCR: 70–150 bp; standard PCR: 200–1000 bp; long-range: 5–40 kb); GC content (40–60%); amplicon Tm (typically 80–90 °C for qPCR); sequence complexity (avoiding repetitive regions); melting curve profile (single peak for specific amplification, multiple peaks for nonspecific products or heterozygotes); and restriction sites for downstream cloning. For high-resolution melt (HRM) analysis, amplicons of 100–300 bp with Tm differences as small as 0.3 °C can distinguish single base changes. Amplicon concentration in PCR typically reaches 0.1–1 μg per 50 μL reaction after 30–35 cycles. For NGS library preparation, amplicon pooling requires balanced representation across targets.""",

    "mistakes": """A common mistake is assuming all amplification products visible on a gel are specific amplicons; primer-dimers (50–100 bp) and nonspecific bands can produce false-positive interpretations. Overcycling PCR beyond the plateau phase (35+ cycles) reduces amplification specificity and generates heteroduplex artifacts. Researchers often fail to confirm amplicon identity by sequencing, relying solely on size estimation from gel electrophoresis. For multiplex PCR, variable amplicon lengths can cause biased amplification of shorter fragments relative to longer ones. Using too much template leads to smeared or nonspecific amplicon bands on gels. In qPCR, selecting an amplicon with secondary structure (ΔG < −6 kcal/mol) reduces amplification efficiency."""
}

# 10. primer-dimer
CONTENT["primer-dimer"] = {
    "mechanism": """Primer-dimers are non-specific double-stranded DNA artifacts formed when two primers hybridize to each other instead of to the target template, and DNA polymerase extends the 3' ends of the annealed primers. They arise from regions of partial or complete complementarity between primer sequences, particularly at the 3' ends where extension initiates. The most problematic form occurs when the 3' end of one primer has 2–4 complementary bases with the 3' end of the other primer, allowing DNA polymerase to extend across and create a covalent primer-primer dimer. These dimers typically appear as short products of 40–100 bp on an agarose gel. In qPCR with SYBR Green, primer-dimers generate fluorescence signals indistinguishable from genuine amplicons unless distinguished by melt curve analysis (primer-dimers melt at lower temperatures, typically 75–82 °C, while specific amplicons melt at 82–90 °C). Primer-dimers can consume reaction components (dNTPs, polymerase) and reduce amplification efficiency of the target, or in severe cases, completely outcompete target amplification. They are particularly problematic in multiplex PCR, low-template PCR, and reactions with high cycle numbers.""",

    "applications": """Primer-dimer detection is a critical quality control step in primer design and PCR optimization. Melt curve analysis after SYBR Green qPCR identifies primer-dimers by their characteristic lower melting temperatures. Primer design software (Primer3, VPrime 2.0, OligoAnalyzer) calculates cross-dimer free energy (ΔG) to flag problematic primer pairs. In diagnostic assays, the presence of primer-dimers reduces sensitivity and specificity, making their elimination essential. Touchdown PCR with decreasing annealing temperatures can reduce primer-dimer formation by favoring specific annealing at higher initial temperatures. Hot-start polymerases (chemically modified or antibody-inhibited) prevent primer-dimer formation during reaction setup by blocking polymerase activity below 70 °C. In multiplex qPCR panels, extensive optimization of primer concentrations and annealing temperatures minimizes dimer artifacts across all primer pairs simultaneously.""",

    "parameters": """Primer-dimer parameters include cross-dimer free energy (ΔG, should be > −8 kcal/mol for acceptable primers); 3' complementarity score (maximum of 2–3 matching bases); number of consecutive matches at 3' ends (0–1 allowed); total number of complementary bases (typically allowed up to 5–6 across full length); amplicon Tm difference from target Tm (primer-dimer Tm is 75–82 °C vs 82–90 °C for specific products); and dimer band visibility on gel electrophoresis. The extent of primer-dimer formation depends on primer concentration (0.05–1 μM), Mg²⁺ concentration (1.5–3 mM), annealing temperature (50–65 °C), and cycle number. In qPCR, a primer-dimer can produce Cq values of 30–38 even in no-template controls, which can be misinterpreted as low-level target contamination.""",

    "mistakes": """A frequent misconception is that primer-dimers only form when primers have extensive complementarity; in fact, as few as 2–3 complementary bases at the 3' ends can lead to dimer formation. Researchers sometimes attribute failed PCR solely to template quality when primer-dimer formation is the culprit. In SYBR Green qPCR, reporting Cq values without melt curve analysis can present primer-dimer signal as genuine amplification. No-template controls (NTCs) are essential but often omitted; a high NTC signal indicates primer-dimer problems. Another common error is repeating a PCR with more cycles (40→45) to compensate for low amplification, which only amplifies primer-dimers further."""
}

# 11. melting-temperature
CONTENT["melting-temperature"] = {
    "mechanism": """Melting temperature (Tm) is defined as the temperature at which 50% of a DNA duplex population is dissociated into single strands under a given set of solution conditions. Tm is calculated using the nearest-neighbor (NN) thermodynamic model, which considers that the stability of a DNA duplex depends on the identity of adjacent base pairs rather than individual base composition alone. The NN model uses experimentally determined enthalpy (ΔH°) and entropy (ΔS°) parameters for each of the 10 possible nearest-neighbor pairs (SantaLucia 1998). The Tm is calculated as Tm = (ΔH°)/(ΔS° + R ln(C/4)) for self-complementary sequences, and Tm = (ΔH°)/(ΔS° + R ln(C)) for non-self-complementary sequences, where C is the total oligonucleotide concentration. Salt corrections are applied because monovalent cations stabilize the duplex by shielding electrostatic repulsion between phosphate backbones: the Owczarzy (2004) formula adjusts Tm for Na⁺ concentrations from 0.01 to 1.0 M. Mg²⁺ corrections account for divalent cation effects (von Ahsen 2001). At 50 mM Na⁺ and 0.25 μM primer concentration, a 20-mer with 50% GC typically has a Tm of 56–62 °C.""",

    "applications": """Tm calculation is essential for determining PCR annealing temperature (typically 3–5 °C below the lower primer Tm). In qPCR, primers are designed with Tm values of 58–60 °C for consistent annealing across targets. Tm is also critical for designing DNA probes (TaqMan, molecular beacons) in hybridization-based assays. In allele-specific PCR, primers are designed with the SNP positioned near the 3' end, where a mismatch reduces Tm by 2–10 °C depending on the mismatch type (e.g., A·C or G·T mismatches are less destabilizing than A·A or C·C). In microarray hybridization, Tm matching across probes (typically 5–10 °C above hybridization temperature) ensures uniform binding stringency. High-resolution melting (HRM) analysis detects sequence variants by monitoring fluorescence as double-stranded DNA dissociates over a 0.1–0.3 °C/s temperature ramp.""",

    "parameters": """Tm calculation inputs include oligonucleotide length (15–60 nt); GC content (20–80%); sequence, specifically the nearest-neighbor dinucleotide composition; monovalent salt concentration (typically 50–200 mM Na⁺ or K⁺); divalent cation concentration (0–10 mM Mg²⁺); and oligonucleotide concentration (0.1–1 μM). The thermodynamic NN parameters include ΔH° (kcal/mol) and ΔS° (cal/mol·K) for Watson-Crick pairs: the most stable is GC (dG/dC ΔH = −11.1 kcal/mol for each adjacent pair), and the least stable is AT (dA/dT ΔH = −6.0 kcal/mol). Strand initiation and symmetry corrections add ΔG contributions of +0.2 to +1.5 kcal/mol. The commonly used Wallace rule (Tm = 2(A+T) + 4(G+C)) approximates the Tm for short oligos (<15 nt) but is inaccurate for longer primers and does not account for sequence context.""",

    "mistakes": """The most common error is using the Wallace rule (2×(A+T) + 4×(G+C)) for primers longer than 15 nt, which can overestimate Tm by 5–10 °C. Another frequent mistake is not accounting for salt concentration: Tm increases approximately 16·log[Na⁺] °C, so using 50 mM Na⁺ default when the PCR buffer contains 50 mM KCl alters the true Tm. Researchers often assume a single Tm value applies to both forward and reverse primers without verifying that the Tm difference between them is less than 5 °C. Mg²⁺ concentration, which stabilizes duplexes more strongly than monovalent cations, is frequently ignored in Tm calculations. Impurities in oligonucleotide synthesis (truncated sequences, failure products) lower the effective Tm of the primer stock."""
}

# 12. gc-content
CONTENT["gc-content"] = {
    "mechanism": """GC content is the percentage of guanine (G) and cytosine (C) nucleotides within a defined DNA or RNA sequence, calculated as 100 × (G + C)/(A + T + G + C). G-C base pairs form three hydrogen bonds, compared to two for A-T pairs, making GC-rich regions more thermally stable. Each G-C pair contributes approximately −3.4 kcal/mol of stacking energy, about 1.6 times more than an A-T pair (−2.1 kcal/mol). This thermodynamic difference means that GC content directly affects DNA melting temperature (Tm), secondary structure formation potential, and DNA compaction. Genomic GC content varies dramatically: the human genome averages approximately 41% GC but ranges from 35% in AT-rich isochores to 60% in GC-rich regions. GC content is not uniform along chromosomes; GC-rich regions often correlate with gene density, active transcription, and recombination hotspots. CpG islands, defined as regions >200 bp with GC content >50% and observed/expected CpG ratio >0.6, are associated with gene promoters. Prokaryotic genomes exhibit wider GC variation, from 25% in Mycoplasma to 75% in Streptomyces, which correlates with growth temperature and nitrogen availability. Coding sequences typically have higher GC content than non-coding regions due to third-codon-position GC bias.""",

    "applications": """GC content analysis is essential in primer and probe design, where 40–60% GC ensures stable annealing and specific binding. In PCR, high GC content (>65%) often requires additives such as DMSO (3–10%), betaine (0.5–2 M), or formamide (1–5%) to reduce secondary structure and improve amplification. Bacterial species identification uses 16S rRNA gene GC profiling. Phylogenetic analysis uses genome-wide GC content to infer evolutionary relationships. In genomics, GC bias correction is applied in NGS library preparation because GC-rich regions are often underrepresented in sequencing reads (GC bias factor of 0.3–0.8 for >60% GC content). CpG island mapping identifies potential promoter regions for epigenetic studies. In metagenomics, GC content distribution helps bin contigs into species-level genome bins (GC heterogeneity within 5% for single species).""",

    "parameters": """GC content parameters include: primer GC content (40–60%); PCR amplicon GC content (40–60%); genomic window GC content analyzed in bins of 100 bp to 1 Mb; CpG observed/expected ratio (>0.6 for CpG islands); third-codon-position GC content (GC3, varies from 30–90% across species); GC skew ((G − C)/(G + C)), which indicates leading/lagging strand bias; and isochore classification (L1: <39%, L2: 39–41%, H1: 41–46%, H2: 46–53%, H3: >53% GC). For PCR optimization of GC-rich templates, additives such as DMSO (3–10% v/v) lower Tm by 2–3 °C per 1% DMSO, betaine (1–2 M) eliminates GC-rich secondary structure, and 7-deaza-dGTP replaces dGTP to disrupt Hoogsteen base pairing.""",

    "mistakes": """A common error is assuming that high GC content always causes PCR failure; with appropriate optimization (additives, touchdown PCR, higher denaturation temperature), many GC-rich templates amplify successfully. Researchers sometimes confuse GC content with GC skew — GC content is the overall proportion, while GC skew measures strand asymmetry. In designing primers for CpG island regions, failing to account for high GC density results in primers that form stable secondary structures. Another misconception is that optimal Tm calculation requires only GC content when, in fact, nearest-neighbor thermodynamics (sequence context) is essential for accurate prediction. Using DMSO concentrations above 10% inhibits Taq polymerase activity by >50%."""
}

# 13. pcr
CONTENT["pcr"] = {
    "mechanism": """PCR exponentially amplifies a specific DNA segment through 20–40 repeated cycles of three temperature-dependent steps: denaturation (94–98 °C, 15–30 seconds) separates double-stranded DNA into single strands; annealing (50–65 °C, 20–40 seconds) allows primers to bind complementary sequences flanking the target region; and extension (72 °C, 30–60 seconds per kb of amplicon) where thermostable DNA polymerase incorporates dNTPs to synthesize the complementary strand. The theoretical amplification factor is 2^n, where n is the number of cycles. In practice, amplification efficiency (E) is less than 100%, and the accumulation follows N = N₀(1 + E)^n. PCR enters a plateau phase after 25–35 cycles when reaction components (dNTPs, primers, polymerase) become limiting and product reannealing competes with primer binding. The PCR product (amplicon) is typically visualized by agarose gel electrophoresis with ethidium bromide or SYBR Green staining, with a detection limit of approximately 1–10 ng of DNA. Taq DNA polymerase, isolated from Thermus aquaticus, has optimal activity at 72–80 °C and a half-life of 40 minutes at 95 °C.""",

    "applications": """PCR is the cornerstone of modern molecular biology, enabling DNA cloning, sequencing template preparation, site-directed mutagenesis, and genotyping. In clinical diagnostics, PCR detects pathogens (Mycobacterium tuberculosis, Neisseria gonorrhoeae, Chlamydia trachomatis, HIV, HBV, HCV) with sensitivity as high as 1–10 genome copies per reaction. In forensics, short tandem repeat (STR) PCR profiling at 20 CODIS loci achieves individual identification probabilities exceeding 99.99%. Quantitative PCR (qPCR) extends PCR to real-time quantification using fluorescence monitoring. Digital PCR (dPCR) partitions the sample into thousands of nanoliter droplets for absolute quantification without standard curves. Reverse-transcription PCR (RT-PCR) extends PCR to RNA targets. Nested PCR uses two sequential amplifications for enhanced specificity and sensitivity. Hot-start PCR uses modified polymerases to prevent nonspecific amplification during reaction setup.""",

    "parameters": """Standard PCR parameters: denaturation temperature (94–98 °C, 15–30 s); annealing temperature (50–65 °C, 20–40 s, typically 3–5 °C below primer Tm); extension temperature (72 °C, 30 s/kb); cycle number (25–40); template DNA amount (1–1000 ng for genomic DNA, 10⁴–10⁷ copies for plasmid); primer concentration (0.1–1 μM each); dNTP concentration (200 μM each); MgCl₂ concentration (1.5–2.5 mM); DNA polymerase concentration (0.025–0.05 U/μL); reaction buffer (10×, typically Tris-HCl pH 8.3–8.8, 50 mM KCl); and final reaction volume (10–50 μL). Touchdown PCR decreases annealing temperature by 0.5–1 °C per cycle for improved specificity.""",

    "mistakes": """The most prevalent error is contamination, where PCR products or genomic DNA from previous reactions produce false-positive results. Strict laboratory practices (separate pre- and post-amplification areas, positive-displacement pipettes, uracil-N-glycosylase carryover prevention) are essential. Overcycling (>35 cycles) leads to nonspecific amplification and heteroduplex formation. Insufficient denaturation time or temperature for GC-rich templates causes secondary structures to persist and block amplification. Using too much template (>500 ng for genomic DNA) can inhibit the reaction. Failure to include appropriate positive controls (known target template) and negative controls (no-template, no-reverse-transcriptase) undermines result interpretation. Incorrect Mg²⁺ concentration (too low reduces yield, too high promotes nonspecific products) is a common optimization oversight."""
}

# 14. taqman-probe
CONTENT["taqman-probe"] = {
    "mechanism": """TaqMan probes are dual-labeled hydrolysis oligonucleotides used in quantitative real-time PCR for sequence-specific detection. The probe contains a fluorophore (reporter dye, typically FAM, VIC, or ROX) covalently attached to the 5' end and a quencher (e.g., TAMRA, BHQ-1, BHQ-2, or MGB) at the 3' end. The probe is designed to anneal to an internal region of the target amplicon, between the forward and reverse primer binding sites, with a Tm 5–10 °C higher than the primers to ensure probe hybridization occurs before primer extension. When the probe is intact and in close proximity to the quencher (typically 10–100 Å distance), fluorescence resonance energy transfer (FRET) suppresses reporter emission. During PCR extension, the 5'-to-3' exonuclease activity of Taq polymerase cleaves the probe, separating the fluorophore from the quencher, resulting in fluorescence emission proportional to the amount of amplified target. Because cleavage requires specific hybridization, TaqMan probes provide sequence-specific detection, eliminating the need for melt curve analysis. Up to 5–6 spectrally distinct fluorophores can be multiplexed in a single reaction.""",

    "applications": """TaqMan probes are the preferred detection chemistry in clinical diagnostic qPCR assays due to their sequence specificity and low background. The CDC 2019-nCoV diagnostic panel uses TaqMan probes targeting the N1 and N2 regions of the SARS-CoV-2 genome. In SNP genotyping, two allele-specific TaqMan probes (each labeled with a different dye, e.g., FAM for wild-type, VIC for variant) in the same reaction enable end-point fluorescence discrimination of homozygous and heterozygous genotypes with >99.5% accuracy. In gene expression analysis, TaqMan probe-based assays achieve detection of 1–10 target copies. Copy number variation (CNV) analysis using TaqMan probes relative to RNase P reference achieves precise gene dosage measurements. In infectious disease monitoring, HIV-1 and HCV viral load assays employ TaqMan chemistry with dynamic ranges spanning 20–10⁷ IU/mL. The MGB (Minor Groove Binder) modification increases probe Tm by 10–18 °C, enabling shorter probes for better mismatch discrimination.""",

    "parameters": """TaqMan probe parameters include probe length (15–30 nt); Tm (68–70 °C, 5–10 °C above primer Tm); GC content (30–80%); concentration (50–250 nM); fluorophore-quencher pair (e.g., FAM-BHQ1, VIC-MGB-NFQ, ROX-BHQ2); maximum G at 5' end (avoided because G quenches FAM); reporter dye selection based on instrument filter channels (FAM: 517 nm, VIC: 554 nm, ROX: 610 nm); MGB modification for Tm enhancement; and HPLC purification required (>90% purity). Multiplex compatibility requires non-overlapping emission spectra with cross-talk compensation. Probe position should avoid the last 10 bases from the 3' end of either primer to ensure cleavage occurs. The 5' end should not start with G, which partially quenches FAM fluorescence.""",

    "mistakes": """A common error is using a probe Tm too close to primer Tm, causing the probe to dissociate before complete cleavage and reducing signal. Researchers sometimes use inadequately purified probes resulting in high background fluorescence from free fluorophores. Another mistake is selecting overlapping fluorophore emission spectra for multiplex reactions without spectral compensation, leading to crosstalk between channels. Placing the probe outside the primer-defined region or covering a polymorphic site can prevent probe binding. Using a Taq polymerase without robust 5'-exonuclease activity (e.g., many proofreading polymerases) eliminates cleavage. Excessive probe concentration (>500 nM) overwhelms quencher capacity and increases background."""
}

# 15. cdna-library
CONTENT["cdna-library"] = {
    "mechanism": """A cDNA library is a collection of cloned complementary DNA (cDNA) molecules representing the expressed mRNA transcripts from a particular tissue, cell type, or developmental stage at the time of RNA extraction. Construction begins with isolation of total RNA (typically 1–10 μg) followed by oligo-dT affinity chromatography to enrich polyadenylated mRNA, which constitutes 1–5% of total RNA. Reverse transcriptase (MMLV or AMV) with oligo-dT primers (18–20 nt) or random hexamers generates first-strand cDNA. Second-strand synthesis uses RNase H (to nick the RNA template) and DNA polymerase I (to fill gaps). Double-stranded cDNA is size-fractionated (often >500 bp), ligated into a plasmid or phage vector (e.g., λZAP, pBluescript) via adapters or restriction linkers, and transformed into competent E. coli cells. A high-quality library should contain at least 1 × 10⁶ independent clones to achieve >99% coverage of the transcriptome (assuming 15,000–25,000 expressed genes at various abundance levels). Normalized libraries reduce the representation of highly abundant transcripts (e.g., actin, GAPDH) by denaturation-renaturation kinetics, enriching rare transcripts by 10–100-fold.""",

    "applications": """cDNA libraries are used for gene discovery (expressed sequence tag sequencing), full-length gene cloning, and functional screening. Expression libraries in vectors such as pET (bacterial), pCDNA3 (mammalian), or pYES (yeast) enable heterologous protein expression for biochemical characterization and antibody production. Subtractive cDNA libraries isolate differentially expressed genes by removing common transcripts between two cell states, enriching specifically up- or down-regulated genes by 10–50-fold. In RNA-seq, cDNA library construction is the first step of next-generation sequencing, incorporating platform-specific adapters (Illumina TruSeq, NEBNext). Yeast two-hybrid screens use cDNA libraries fused to activation domains to identify protein-protein interactions. In metagenomics, cDNA libraries from environmental samples reveal actively transcribed microbial genes. Full-length cDNA resources such as the Mammalian Gene Collection (MGC) provide sequence-validated open reading frame clones for 15,000+ human genes.""",

    "parameters": """cDNA library parameters include RNA integrity (RIN > 8.0 for full-length libraries, > 6.0 for standard); mRNA enrichment efficiency (A260 A₂₆₀/A₂₈₀ ratio > 1.8); first-strand synthesis yield (typically 20–50% of input RNA); cloning efficiency (10⁶–10⁹ CFU/μg vector); insert size range (500–4000 bp, average 1.5–2 kb); average insert length (>1 kb for full-length libraries); library titer (10⁹–10¹¹ CFU/mL for amplified libraries); redundancy (genome coverage = clone number × average insert size / transcriptome size); and percentage of full-length clones (typically 30–70% containing complete ORF). Normalization reduces abundant transcript representation by 10–100-fold, increasing library complexity by 3–5-fold. Vector systems commonly use ampicillin or kanamycin selection at 50–100 μg/mL.""",

    "mistakes": """A common error is using degraded RNA (RIN < 6) for cDNA library construction, resulting in underrepresentation of 5' transcript ends and truncated clones. Researchers often over-amplify libraries, which leads to loss of complexity due to preferential amplification of smaller inserts. Insufficient bacterial transformation efficiency (<10⁶ CFU/μg) fails to capture low-abundance transcripts. Another misconception is that a normalized library contains an equal representation of every transcript; normalization reduces but does not eliminate abundance differences (rare transcripts may still be 10–50-fold less abundant than abundant ones). Cloning artifacts such as concatemerization or adapter-dimer contamination can reduce the proportion of clones with genuine inserts. Sequencing errors in early EST projects were often propagated as database artifacts due to lack of validation."""
}

# 16. annealing-temperature
CONTENT["annealing-temperature"] = {
    "mechanism": """Annealing temperature (Ta) is the temperature at which primers hybridize to their complementary target sequences during the PCR cycle. It is the single most critical parameter for PCR specificity and yield. Primer-template duplex formation follows the principles of nucleic acid thermodynamics: at temperatures above the primer melting temperature (Tm), few primer molecules are bound to template; at temperatures significantly below Tm, primers bind but may form mismatched duplexes with similar (non-target) sequences, leading to nonspecific amplification. The optimal Ta is typically 3–5 °C below the lower Tm of the two primers, providing sufficient stringency for specific hybridization while allowing adequate primer-template duplex stability. During PCR, the annealing step lasts 20–40 seconds, during which both primer diffusion to the template and duplex formation occur. The thermal cycler block temperature must equilibrate rapidly; modern instruments achieve ramp rates of 3–5 °C/s. For qPCR, annealing is often combined with extension at 60 °C in a two-step cycling protocol (95 °C denaturation, 60 °C anneal/extend) for assays with primers having Tm values of 58–60 °C. Touchdown PCR uses an initial Ta of 10 °C above the optimal Ta, decreasing by 0.5–1 °C each cycle over 10–20 cycles, then continuing at the final Ta for the remaining cycles, progressively enriching specific products.""",

    "applications": """Annealing temperature optimization is performed for every new primer pair using temperature gradient PCR, where replicate reactions across a 10–20 °C temperature range (e.g., 50–70 °C) identify the Ta that produces the brightest specific band with minimal nonspecific products. In qPCR, a single annealing temperature is typically used (60 °C) with primers designed to have matching Tm values. For allele-specific PCR, the Ta is set 1–2 °C below the perfectly matched primer's Tm but above the mismatch-containing primer's effective Tm, enabling discrimination of single-base differences. In multiplex PCR, a compromise Ta is selected that accommodates all primer pairs, often determined by the primers with the lowest Tm. For GC-rich templates, higher Ta (55–65 °C) combined with additives improves specificity. Bisulfite-converted DNA requires lower Ta (50–55 °C) due to reduced sequence complexity (only three bases in converted DNA). In long-range PCR (10–30 kb), annealing-extension is combined at 65–68 °C using specialized polymerase blends.""",

    "parameters": """Annealing temperature parameters include primer Tm (52–58 °C for standard PCR, 58–60 °C for qPCR); optimal Ta (Ta_opt = 0.3 × Tm_primer + 0.7 × Tm_product − 14.9, or simpler: Tm − 3 to 5 °C); annealing time (20–40 s); temperature gradient range (50–70 °C for optimization); touchdown start Ta (10 °C above optimal); touchdown decrement (0.5–1 °C/cycle); touchdown cycles (10–20); final Ta cycles (15–25). For multiplex PCR, the Ta should be within 2 °C of all primer pairs' optimal Tms. For GC-rich templates (>65% GC), Ta is often increased by 2–5 °C. For degenerate primers, Ta of 42–50 °C is used in initial cycles.""",

    "mistakes": """The most common mistake is using a Ta equal to the primer Tm, which results in minimal primer binding and poor yield. Another error is failing to perform a temperature gradient when using new primers, leaving significant optimization potential untapped. Researchers often assume that two primers with identical GC content will have identical Tms; in reality, nearest-neighbor thermodynamics produce different Tms for different sequences even with identical GC percentage. In multiplex PCR, setting a single Ta without considering the Tm spread across primer pairs causes uneven amplification. Touchdown PCR is underutilized for problematic templates; many researchers attempt fixed-Ta PCR repeatedly instead of applying a touchdown gradient. Using an incorrect thermal cycler calibration can shift actual Ta by 1–3 °C from the programmed value."""
}

# 17. dna-polymerase
CONTENT["dna-polymerase"] = {
    "mechanism": """DNA polymerases are enzymes that synthesize DNA from deoxyribonucleoside triphosphates (dNTPs) using a single-stranded DNA template and a primer with a free 3'-hydroxyl group. They catalyze nucleotidyl transfer in the 5'-to-3' direction, incorporating dNMPs with exquisite base selectivity. The mechanism involves a two-metal-ion catalysis (Mg²⁺ ions coordinated by aspartate residues in the active site) that deprotonates the 3'-OH and stabilizes the pyrophosphate leaving group. DNA polymerases exhibit remarkable fidelity: Taq polymerase has an error rate of approximately 1 × 10⁻⁴ to 2 × 10⁻⁵ errors per base (one error per 10,000–50,000 incorporated nucleotides). Proofreading polymerases (Pfu, Phusion, KOD) possess 3'-to-5' exonuclease activity that removes misincorporated bases, reducing error rates to 1 × 10⁻⁶ to 5 × 10⁻⁷ errors per base. DNA polymerases differ in thermostability, extension rate, processivity, and fidelity. Taq (from Thermus aquaticus) has a half-life of 40 min at 95 °C and extends at 60 nt/s; Pfu (from Pyrococcus furiosus) has a half-life of 240 min at 95 °C and extends at 15 nt/s; Phusion has a half-life of 120 min at 98 °C and extends at 100 nt/s. Family B polymerases (Pfu, Phusion) have 3'-5' exonuclease activity while Family A polymerases (Taq, Tth) lack it.""",

    "applications": """DNA polymerases are the core enzymes in PCR, DNA sequencing (Sanger and next-generation), DNA labeling (nick translation, random priming), site-directed mutagenesis (inverse PCR, overlap extension), and molecular cloning (blunt-end and TA cloning). Taq polymerase is the standard for routine PCR and incorporates A-overhangs enabling TA cloning. High-fidelity polymerases (Phusion, Q5, KOD) are essential for cloning and sequencing where error minimization is critical. In qPCR, specific polymerases with modified reaction kinetics improve accuracy. Hot-start polymerases (chemically modified or antibody-inhibited) prevent nonspecific amplification during reaction setup. Reverse transcriptases (MMLV, AMV) are RNA-dependent DNA polymerases used for RT-PCR. Terminal deoxynucleotidyl transferase (TdT) is a template-independent DNA polymerase used for dA-tailing in cloning and DNA labeling for TUNEL assays. Bacteriophage DNA polymerases (T4, T7) are used for specific in vitro DNA synthesis applications.""",

    "parameters": """DNA polymerase parameters include extension rate (15–100 nt/s at 72–98 °C); processivity (10–1000 nt per binding event); fidelity (error rate per base: 10⁻⁴ to 10⁻⁷); thermostability (half-life at 95 °C: 40 min for Taq, 240 min for Pfu); exonuclease activity (3'-5' proofreading yes/no); optimal temperature (72–80 °C for Taq, 72–75 °C for Pfu, 72–98 °C for Phusion); optimal Mg²⁺ concentration (1.5–2.5 mM for Taq, 2–4 mM for Pfu); optimal pH (8.0–9.0); dNTP Km (2–10 μM); salt sensitivity (50 mM KCl optimal for Taq, 100 mM for Pfu); and inhibitor sensitivity (SDS, EDTA, guanidine). Enzyme concentration in PCR is typically 0.025–0.05 U/μL. The Sanger sequencing enzyme has a modified ratio of dNTPs to ddNTPs (typically 50:1 to 100:1)."""

,
    "mistakes": """A common error is using Taq polymerase for cloning applications requiring high fidelity, resulting in mutations in the cloned product. Researchers often use excess enzyme (>0.1 U/μL), which can cause nonspecific amplification and primer-dimer formation. Another mistake is assuming all proofreading polymerases produce blunt ends suitable for blunt-end cloning; some leave 3' A-overhangs while others produce blunt ends. For long-range PCR (>5 kb), using a non-proofreading polymerase yields low product due to polymerase stalling at damaged bases. Mixing two polymerases with incompatible buffer conditions (e.g., Taq buffer components in Pfu reaction) inhibits both enzymes. Many proofreading polymerases cannot use uracil-containing templates, making them unsuitable for bisulfite-converted DNA PCR without specific uracil-tolerant variants."""
}

# 18. multiplex-pcr
CONTENT["multiplex-pcr"] = {
    "mechanism": """Multiplex PCR simultaneously amplifies multiple target sequences in a single reaction by including more than one primer pair (typically 2–20 pairs). Each primer pair targets a different genomic locus, producing amplicons of distinct sizes that can be resolved by gel electrophoresis, capillary electrophoresis, or detected by different fluorophores in real-time PCR. The fundamental challenge in multiplex PCR is balancing amplification efficiency across all targets: primer pairs must have compatible Tm values (within 2–5 °C), minimal cross-reactivity (no significant complementarity between primers from different pairs), and non-overlapping amplicon size ranges. Primer concentrations are often adjusted asymmetrically (0.05–0.5 μM for different pairs) to normalize final product yields. The reaction uses higher concentrations of dNTPs (300–500 μM each), MgCl₂ (2.5–4 mM), and DNA polymerase (typically 2–4 × standard) to support multiple extension reactions simultaneously. Multiplex assays require extensive optimization: primer ratios, annealing temperature, extension time, and buffer composition (Tris-HCl pH 8.3–8.8, KCl, (NH₄)₂SO₄). GC-rich and AT-rich targets within the same multiplex require balancing with DMSO (2–5%) or betaine (1 M). PCR cycling with a longer combined annealing-extension step at 60 °C (60–90 s) is common for 5–10-plex assays. Amplicon detection by capillary electrophoresis uses fluorescent dye-labeled primers (FAM, HEX, NED, ROX, PET) with GeneScan size standards.""",

    "applications": """Multiplex PCR is widely used in clinical diagnostics: respiratory pathogen panels detect 15–30 viruses and bacteria simultaneously (BioFire FilmArray, ePlex); gastrointestinal pathogen panels detect 15–25 enteric pathogens; and meningitis/encephalitis panels detect 14 pathogens from CSF. In forensic DNA profiling, the AmpFlSTR Identifiler and PowerPlex systems amplify 15–24 STR loci plus amelogenin simultaneously, enabling human identification from 0.5–1 ng DNA with random match probabilities <10¹⁷. In oncology, multiplex PCR panels detect hotspot mutations in EGFR, KRAS, BRAF, and NRAS from FFPE tissue. Microsatellite instability (MSI) testing uses a 5-marker multiplex panel (BAT-25, BAT-26, NR-21, NR-24, MONO-27). In agricultural biotechnology, multiplex GMO detection identifies transgenic elements (35S, NOS, FMV) across multiple crop species in a single assay. Microbial community profiling uses 16S rRNA gene multiplex PCR with barcoded primers for Illumina sequencing. In virology, multiplex RT-PCR panels detect influenza A subtypes (H1N1, H3N2, H5N1) and influenza B lineages simultaneously.""",

    "parameters": """Multiplex PCR parameters include number of targets (2–20); amplicon size range (80–600 bp, with 20–50 bp separation between targets); primer Tm matching (within 2 °C for all pairs); primer concentrations (asymmetric, 0.05–0.5 μM); dNTP concentration (300–500 μM each); MgCl₂ (2.5–4 mM); DNA polymerase (0.05–0.1 U/μL); annealing/extension temperature (57–60 °C); extension time (60–90 s for 5–10 targets); cycle number (30–40); and buffer composition often including (NH₄)₂SO₄ for balanced amplification. For qPCR multiplex, up to 5–6 fluorophore channels can be used (FAM, VIC, ROX, Cy5, Texas Red). In capillary electrophoresis multiplex, 4–5 fluorescent dyes in different wavelengths enable size-based separation with 0.5–1 bp resolution. Touchdown protocols (65 to 55 °C at −0.5 °C/cycle) improve multiplex specificity.""",

    "mistakes": """The most common error in multiplex PCR is combining primer pairs without checking for cross-primer complementarity, leading to primer-dimer artifacts in the multiplex reaction. Researchers often use equal primer concentrations for all targets instead of optimizing ratios to balance amplification. Another frequent mistake is designing amplicons with insufficient size separation (<15 bp difference), making gel or capillary resolution unreliable. Adding too many targets (15+) without careful optimization causes dropout of low-efficiency targets. Poor template quality disproportionately affects longer amplicons in the multiplex, resulting in allele dropout or locus dropout. The absence of a positive amplification control (e.g., RNase P, GAPDH, or 18S rRNA) prevents distinguishing true negatives from reaction failure. Overly long storage for rehydrated multiplex primers leads to differential primer degradation and unbalanced amplification."""
}

# 19. nested-pcr
CONTENT["nested-pcr"] = {
    "mechanism": """Nested PCR is a two-stage amplification strategy designed to dramatically improve specificity and sensitivity for detecting low-abundance targets. In the first round (outer PCR, 20–30 cycles), an external primer pair amplifies a larger fragment (typically 500–1500 bp) containing the target region. In the second round (inner PCR, 25–35 cycles), a second primer pair (the "nested" primers) binds within the product of the first reaction, amplifying a shorter internal fragment (typically 100–400 bp). The nested primers require that the first-round product contained the correct internal sequence — any nonspecific product from the first round that lacks the internal target region cannot be amplified in the second round. This two-tier specificity provides a 10³- to 10⁶-fold increase in selectivity compared to single-round PCR. Each round uses 1–2 μL of the previous reaction product (or 1:10–1:100 dilution) as template, minimizing carryover of primers and other components. A variation, semi-nested PCR, uses one outer primer and one inner primer in the second round for additional flexibility. The total amplification power approaches 2^(n₁+n₂) theoretically, though practical yields are limited by dNTP and polymerase availability. Nested PCR can detect as few as 1–10 target copies in complex DNA backgrounds containing up to 1 μg of genomic DNA.""",

    "applications": """Nested PCR is the method of choice for detecting low-copy-number pathogens such as HIV-1 proviral DNA, hepatitis B virus in seronegative individuals, and Mycobacterium tuberculosis in paucibacillary specimens. In archaeological and paleogenetic studies, nested PCR amplifies ancient DNA (aDNA) from Neanderthal bones and mummified tissues, where template is highly fragmented and present at 0.1–1% of total extractable DNA. In molecular oncology, nested PCR detects minimal residual disease (MRD) in leukemia by amplifying rearranged immunoglobulin (IgH) or T-cell receptor (TCR) gene sequences with sensitivities of 10⁻⁴ to 10⁻⁶ (one leukemic cell in 10,000–1,000,000 normal cells). In prenatal diagnosis, nested PCR of cell-free fetal DNA from maternal plasma detects fetal RhD status and paternally inherited mutations. In forensic analysis, nested PCR amplifies degraded DNA from touch evidence, bone fragments, and hair shafts where template levels are below 100 pg. In HLA typing, nested PCR amplifies specific allele groups for high-resolution typing at Class I and Class II loci. In 16S rRNA metagenomic analysis, nested PCR increases detection sensitivity for low-abundance bacterial taxa in microbiome studies.""",

    "parameters": """Nested PCR parameters include outer amplicon length (300–1500 bp); inner amplicon length (100–350 bp); first-round cycles (20–30); second-round cycles (25–35); first-round annealing temperature (52–58 °C); second-round annealing temperature (55—62 °C); inter-round transfer volume (1–2 μL or 1:10–1:100 dilution); outer primer concentration (0.2–0.5 μM each); inner primer concentration (0.2–0.5 μM each); MgCl₂ concentration (1.5–2 mM); dNTP concentration (200 μM each); and Taq polymerase concentration (0.025–0.05 U/μL per round). Template input for the first round is typically 50–500 ng genomic DNA. For second-round template, 1 μL of a 1:50 dilution of the first-round product avoids excess primer carryover. Sensitivity can reach single-copy detection in 1 μg genomic DNA with optimized conditions.""",

    "mistakes": """The most critical error in nested PCR is amplicon carryover contamination: transferring first-round products can aerosolize and contaminate subsequent reactions, producing false positives. Dedicated pre- and post-amplification areas, aerosol-resistant filter tips, and uracil-N-glycosylase (UNG) carryover prevention are essential. Beginners often transfer too much first-round product (>5 μL) into the second round, causing inhibition from leftover primers, dNTPs, or Mg²⁺. Excessive cycles in the first round (35+) can cause plateau-phase artifacts. A false sense of specificity is another pitfall: while nested PCR reduces nonspecific amplification, it can amplify primer-dimer artifacts in both rounds, producing a visible band of the wrong size. Not confirming nested products by sequencing or RFLP analysis can lead to misidentification. Hot-start polymerases are recommended for both rounds to prevent mispriming during reaction setup, especially when the nested primers have partial complementarity to outer primers."""
}

def expand_file(filepath, term):
    """Insert 4 new sections between definition and in-practice."""
    with open(filepath, "r") as f:
        content = f.read()

    c = CONTENT[term]

    sections_html = f"""
    <section class="section" id="mechanism">
      <h2>Mechanism / How It Works</h2>
      <p>{c["mechanism"]}</p>
    </section>

    <section class="section" id="applications">
      <h2>Applications in Research</h2>
      <p>{c["applications"]}</p>
    </section>

    <section class="section" id="parameters">
      <h2>Key Parameters / Variables</h2>
      <p>{c["parameters"]}</p>
    </section>

    <section class="section" id="mistakes">
      <h2>Common Mistakes / Misconceptions</h2>
      <p>{c["mistakes"]}</p>
    </section>
"""

    # Standard format: after </section> of definition, before in-practice
    pattern = r'(</section>\s*\n\s*<section class="section" id="in-practice">)'
    result = re.sub(pattern, sections_html + r"\1", content, count=1, flags=re.DOTALL)

    if result == content:
        # Legacy format: after def-box </div>, before detail div
        # Pattern: def-box closing, then optional CTA link, then detail div
        pattern2 = r'(</div>\s*\n\s*<a href="[^"]*" class="cta">.*?</a>\s*\n\s*<div class="detail")'
        m = re.search(pattern2, content, re.DOTALL)
        if m:
            result = re.sub(pattern2, r'</div>\n' + sections_html + r'\1', content, count=1, flags=re.DOTALL)
        else:
            # Try without CTA link
            pattern3 = r'(</div>\s*\n\s*<div class="detail")'
            result = re.sub(pattern3, r'</div>\n' + sections_html + r'\1', content, count=1, flags=re.DOTALL)

    if result == content:
        print(f"  ⚠ WARNING: Could not find insertion point in {filepath}")
        return False

    with open(filepath, "w") as f:
        f.write(result)
    return True


def count_content_words(filepath):
    """Count words in section content (excluding nav/footer/header)."""
    with open(filepath, "r") as f:
        content = f.read()
    # Extract content between <main> and </main>
    main_match = re.search(r'<main[^>]*>(.*?)</main>', content, re.DOTALL)
    if not main_match:
        return 0
    main_content = main_match.group(1)
    # Remove all HTML tags
    text = re.sub(r'<[^>]+>', ' ', main_content)
    text = re.sub(r'&[a-z]+;', ' ', text, flags=re.IGNORECASE)
    words = text.split()
    return len(words)


def main():
    glossary_dir = GLOSSARY_DIR
    results = []

    for term in TERMS:
        filename = f"{term}.html"
        filepath = os.path.join(glossary_dir, filename)

        if not os.path.exists(filepath):
            print(f"  SKIP: {filename} (file not found)")
            results.append((term, "SKIPPED - not found"))
            continue

        before = count_content_words(filepath)
        print(f"  {filename}: processing ({before} words before)...", end=" ")

        success = expand_file(filepath, term)
        if success:
            after = count_content_words(filepath)
            added = after - before
            print(f"OK ({before} → {after} words, +{added})")
            results.append((term, after))
        else:
            print("FAILED")
            results.append((term, "FAILED"))

    print("\n" + "=" * 60)
    print("COMPLETION SUMMARY")
    print("=" * 60)
    for term, wc in results:
        if isinstance(wc, int):
            print(f"  {term+'.html':30s} {wc:>5} words")
        else:
            print(f"  {term+'.html':30s} {wc}")

    # Verify 3 random files
    import random
    processed = [(t, w) for t, w in results if isinstance(w, int)]
    if len(processed) >= 3:
        samples = random.sample(processed, 3)
        print("\n" + "-" * 60)
        print("VERIFICATION (3 random files)")
        print("-" * 60)
        for term, wc in samples:
            f = os.path.join(glossary_dir, f"{term}.html")
            actual = count_content_words(f)
            print(f"  {term+'.html':30s} {actual:>5} words in main content")
            if actual < 600:
                print(f"  {'':30s} ⚠ WARNING: below 600 word target")
            else:
                print(f"  {'':30s} ✓ above 600 word target")


if __name__ == "__main__":
    main()
