#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────
# VigyanLLM — PostgreSQL Migration Guide: EC2-local → AWS RDS
# Run these steps MANUALLY (one-time migration, not automated).
# ──────────────────────────────────────────────────────────────────────────

echo "=============================================="
echo "VigyanLLM — Migrate PostgreSQL to AWS RDS"
echo "=============================================="
echo ""
echo "Step 1: Create RDS instance"
echo "  AWS Console → RDS → Create database"
echo "  Engine: PostgreSQL 16"
echo "  Instance: db.t3.micro (free tier)"
echo "  Region: ap-south-1 (Mumbai)"
echo "  DB name: vigyanpilot"
echo "  Master username: vigyan"
echo "  Master password: (generate a strong one)"
echo "  Storage: 20GB gp3"
echo "  Public access: No (same VPC as EC2)"
echo "  VPC Security Group: Allow inbound 5432 from EC2 security group"
echo ""
echo "Step 2: On EC2, dump local database"
echo "  PGPASSWORD=<old-pw> pg_dump \\"
echo "    -h localhost -U vigyan -d vigyanpilot \\"
echo "    --no-owner --no-acl > /tmp/vigyanpilot_dump.sql"
echo ""
echo "Step 3: Restore to RDS"
echo "  PGPASSWORD=<rds-pw> psql \\"
echo "    -h <rds-endpoint>.ap-south-1.rds.amazonaws.com \\"
echo "    -U vigyan -d vigyanpilot < /tmp/vigyanpilot_dump.sql"
echo ""
echo "Step 4: Update .env"
echo "  DATABASE_URL=postgresql://vigyan:<rds-pw>@<rds-endpoint>:5432/vigyanpilot"
echo ""
echo "Step 5: Restart backend"
echo "  pkill gunicorn && cd ~/vigyanpilot && gunicorn --bind 0.0.0.0:5000 wsgi:app &"
echo ""
echo "Step 6: Update GitHub Secret"
echo "  Add/update DATABASE_URL in GitHub Secrets for CI/CD"
echo ""
echo "=============================================="
echo "Benefits:"
echo "  • Database survives EC2 termination"
echo "  • Automated backups (daily snapshots)"
echo "  • Multi-AZ failover (optional)"
echo "  • No 'docker compose' dependency on EC2"
echo "=============================================="
